### ISSUE TITLE
Split the standard library into narrower scoped packages

### ISSUE THREAD

**Issue by dlespiau** [jkcfg/jk#100]
At the moment the standard library namespace is were we put ALL the things. We could split things a bit: `std/io`, `std/fs`, `std/param` (we already have `std.param`!).

**Comment by squaremo** [comment]
Two thoughts:

 1. Is this possible to arrange with rollup.js?
 2. We'll have to be careful to only include std_deferred in one place, so it gets instantiated just once. No globals!

**Comment by dlespiau** [comment]
There's a decision that would have impact on answers to those questions: should the namespacing be done with:

- modules - eg. `import { info } from 'std/fs`) or
- objects - eg. parameters functions are in a sub-object at the moment `std.param.String()`

**Comment by dlespiau** [comment]
master now supports stdlib modules while preserving compatibility with the current API. I've defined:

- `@jkcfg/std/param`
- `@jkcfg/std/fs`

We may want to do more, but that's for some other issue.
