### ISSUE TITLE
Include mix (and thus patch) from @jkcfg/mixins in the standard library

### ISSUE THREAD

**Issue by dlespiau** [jkcfg/jk#117]
`mix()` seems to be a useful and general primitive. We should include a version of it in the standard library so people don't have to setup `npm` and a `package.json` to have access to this primitive.

**Comment by squaremo** [comment]
We can just add it, and deprecate jkcfg/mixins, though it would be nice to do #100 first so it can be a submodule.

**Comment by dlespiau** [comment]
This was done in #140. Closing.
