### ISSUE TITLE
Loading resources

### ISSUE THREAD

**Issue by squaremo** [jkcfg/jk#134]
While writing chart examples, I realised any packaged chart with templates in files would need to load those templates as resources -- that is, relative to the installed package, rather than relative to the working (or input) directory.

Here are some sketches:

**`std.resource()`**

Simply put: a procedure that acts like `read` _except_ that it reads relative to the module directory.
This would need the runtime to know where the call site is; and I'm not sure that's possible.

**`import res from 'resource:foo.yaml'`**

i.e., reuse the import mechanism. This has the benefit that it's done during module loading, so paths can be calculated relative to the module path easily.

The big drawback is that the resource paths must be static.

**`import resource from 'std/resource'`**

A magic module that provides a `read`-like procedure specialised to the importing module path.
Implementing this may open I/O up to abuses, since it will probably need a path (or some indirection) to be embedded in the JavaScript code to be sent to the runtime. It also would be tricky to provide a shim for, when testing.

**Comment by dlespiau** [comment]
with #135 merged, let's close this in favour of more detailed fixes/improvements if needed.
