### ISSUE TITLE
Run one-liner scripts from the command line

### ISSUE THREAD

**Issue by dlespiau** [jkcfg/jk#174]
We could provide an option to run simple scripts directly from the command line:

To display the cluster name defined in a [footloose](https://github.com/weaveworks/footloose) configuration:
```
jk run -c "read('footloose.yaml').then(c => log(c.cluster.name)"
```

To implement this, we would have a small wrapper we execute instead of the command line (needs master to use these imports, see: https://github.com/jkcfg/jk/blob/master/docs/deprecations.md).

```js
import { log, write, read } from '@jkcfg/std';
import { dir, info } from '@jkcfg/std/fs';
import * as param from '@jkcfg/std/param';

%s;
```

and the content of the `-c` option is injected in that wrapper.

This needs to have:
- An example in the `jk run` help text
- A e2e test

**Comment by squaremo** [comment]
:+1: for both this and running a module `jk run -m "@myorg/charts/foobar"` :-)
