### ISSUE TITLE
Handling Kubernetes configmaps

### ISSUE THREAD

**Issue by jaxxstorm** [jkcfg/jk#182]
Apologies for the trivial question, I'm new to ECMAScript/Javascript in general.

How are configmaps handles? I want to recreate a configmap witha YAML doc in it, for example

```
apiVersion: v1
data:
  config.yaml |
    multi-line-doc-here
```

How would this look in jk?

**Comment by squaremo** [comment]
If you use the `@jkcfg/kubernetes` package, you can do something like

```js
import { read, log, Encoding } from '@jkcfg/std';

async function configFromFile(file) {
  const yaml = await read(file, { encoding: Encoding.String });
  return {
    [file]: yaml,
  };
}

configFromFile('config.yaml').then(log);
```

**Comment by dlespiau** [comment]
Without the `@jkcfg/kubernetes` support library it would look like (done with 0.2.5):

```js
$ cat cm.js 
import * as std from '@jkcfg/std';

const config = `this file
has multiple
lines
`;

const cm = {
  apiVersion: 'v1',
  kind: 'ConfigMap',
  data: {
    'config.yaml': config,
  },
};

std.write(cm, 'foo-cm.yaml');

$ jk run -v cm.js 
wrote foo-cm.yaml

$ cat foo-cm.yaml 
apiVersion: v1
data:
  config.yaml: |
    this file
    has multiple
    lines
kind: ConfigMap
```

The '@jkcfg/kubernetes' npm module has support for adding types to kubernetes objects and various utility functions.

We are definitely lacking in documentation here. An excellent reminder we need to do better very soon :)

**Comment by dlespiau** [comment]
There is one pretty bad limitation right now: if you want to express the content of `config.yaml` as a js object (in the example above, you would like the `config` variable to be an js object, not a string), we need to transform that object into a string but the standard library doesn't expose such functionality at the moment and that's issue #148 if you want to follow progress there.

**Comment by jaxxstorm** [comment]
A-ha! Thanks @dlespiau  that examples is awesome, I'll try contribute this to the docs as well.

**Comment by dlespiau** [comment]
For the example, we could start an `examples` directory in the `jk` repository with the above, might as well start somewhere. I'd like to move all examples in this very directory soon-ish.

**Comment by sh0rez** [comment]
> There is one pretty bad limitation right now: if you want to express the content of `config.yaml` as a js object (in the example above, you would like the `config` variable to be an js object, not a string), we need to transform that object into a string but the standard library doesn't expose such functionality at the moment and that's issue #148 if you want to follow progress there.

What about `JSON.stringify()`? `json` is valid `yaml`, so if it is available ... Looks ugly afterwards but works?

**Comment by dlespiau** [comment]
There is one interesting behaviour of `JSON.stringify`. It's output depends on the order of the object key insertion:

```
$ cat stringify.js 
import * as std from '@jkcfg/std';

const o = {
  a: 1,
  b: 2,
};

std.log(JSON.stringify(o));
$ jk run stringify.js
{"a":1,"b":2}

$ cat stringify.js 
import * as std from '@jkcfg/std';

const o = {
  b: 2,
  a: 1,
};

std.log(JSON.stringify(o));

$ jk run stringify.js
{"b":2,"a":1}
```

I'd like to be able to lift the determinism of `std.write` (canonical YAML/JSON with key ordering). It could be a very simple API, I have in mind something like:

```
import * as std from '@jkcfg/std';

const o = {
  b: 2,
  a: 1,
};

std.log(std.Value(o).asString());
```
