### ISSUE TITLE
determine if file run directly or imported

### ISSUE THREAD

**Issue by bryanlarsen** [jkcfg/jk#186]
Is there some way for a file to tell if it was imported or run directly via `jk run`?

The equivalent question in node.js:  https://stackoverflow.com/questions/6398196/node-js-detect-if-called-through-require-or-directly-by-command-line

**Comment by dlespiau** [comment]
There isn't at this time. Out of curiosity, what is the use case for this?

**Comment by bryanlarsen** [comment]
use case described here:  https://github.com/jkcfg/jk/issues/125#issuecomment-488285182

right now when I run `jk run parent.js` it ouputs 34 files.    If I can just do `jk run child.js` to only get a couple of files of output it'll be much easier to debug.

**Comment by dlespiau** [comment]
Ah I see. That's something that could be solved if both parents and children implement the same "protocol" (`export default [objects]`)  and if `jk generate` could be called with either parent or child. Seems like a nicer way to solve the use case.

**Comment by dlespiau** [comment]
Given that `jk generate` can now be used as I described in my latest comment, going to close this. I'd rather not introduce too many things that will result in different code paths (and so potentially different results) depending on how the script is invoked.

Do re-open if you disagree!
