### ISSUE TITLE
std.mix should be curried

### ISSUE THREAD

**Issue by dlespiau** [jkcfg/jk#201]
It'd be nice to be able to using currying with std.mix so we can nicely express a complex transform we can apply to several objects.

[Ramda](https://github.com/ramda/ramda) does it for the vast majority of its functions, we could have a look at how they do it.

**Comment by squaremo** [comment]
You can't curry a function that takes varargs, because you don't know when you've provided all the arguments. But you can certainly make it higher-order -- that is,

```
function mix(...patches) {
  return v => patches.reduce((acc, fn) => fn(acc), v);
}
```

**Comment by dlespiau** [comment]
Ah yes, makes sense! Not sure the `mix` in the std lib should be a high order function itself, users can always declare such a thing with:

```js
const f = v => mix(v, ...)
```

Let's close this for now.
