### ISSUE TITLE
Document parse/unparse (std tour + example)

### ISSUE THREAD

**Issue by dlespiau** [jkcfg/jk#207]
We need to document those functions:

- They should have their own section in the tour: https://jkcfg.github.io/#/documentation/
- We should have examples in `examples/`. Say building a ConfigMap with a file being a YAML file generated from a js object.

**Comment by squaremo** [comment]
- Tour stop: https://jkcfg.github.io/#/documentation/std-parse
 - Example: https://github.com/jkcfg/jk/pull/336

**Comment by squaremo** [comment]
#336 is now merged.
