### ISSUE TITLE
Consider using `path` instead of `file` in the generate struct

### ISSUE THREAD

**Issue by dlespiau** [jkcfg/jk#219]
When showing `jk generate` to someone, he found the use of the `file` key confusing:

```js
export default [
  { value: dashboard('apiserver'), file: 'dashboard.json' },
]
```

It wasn't clear at first glance if `file` was the content to write or the path of the file to write. We may want to rename `file` to `path` to lift this ambiguity.

**Comment by squaremo** [comment]
or `filename`? (though that's usually the base name, isn't it)

**Comment by dlespiau** [comment]
It's also longer to type than `path` :)

**Comment by squaremo** [comment]
`p`?

**Comment by dlespiau** [comment]
:trollface: :grin:
