### ISSUE TITLE
Error compiling from source

### ISSUE THREAD

**Issue by moderation** [jkcfg/jk#225]
I'm hitting an error trying to compile from source. I'm on Xubuntu 18.04 (4.15.0-54) with node v12.5.0 and npm  v6.9.0.

```
make dep
cd std && npm ci
npm WARN prepare removing existing node_modules/ before installation
npm ERR! Cannot read property 'resolve' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2019-07-02T04_32_12_712Z-debug.log
Makefile:38: recipe for target 'std-install' failed
```
From the log file
```
52 verbose stack TypeError: Cannot read property 'resolve' of undefined
52 verbose stack     at regFetch (/usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/index.js:76:23)
52 verbose stack     at fromManifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/tarball.js:55:3)
52 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/tarball.js:38:25
52 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
52 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
52 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
52 verbose stack     at Promise._settlePromiseCtx (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:606:10)
52 verbose stack     at _drainQueueStep (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:142:12)
52 verbose stack     at _drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
52 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
52 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
52 verbose stack     at processImmediate (internal/timers.js:439:21)
```
Any ideas?

**Comment by moderation** [comment]
Managed to get past this. A bunch of npm updating, npx re-installing, npm re-installing, upgrading global packages etc. Make the `go get` cross platform install of `go-jsonnet` and `cue` very appealing. Onto the next stage.

**Comment by dlespiau** [comment]
Eeek, it does sound like it was a bit of  journey. We provide a docker image with everything setup and the build becomes a single line:

```
./run-in-docker.sh make dep jk
```

It's in the README, but maybe we should make that more prominent. The first contact with the build is indeed a bit daunting: v8, flabutters, cgo, go and the js ecosystem. It's hard to beat the (pure) go distribution story but, maybe when using the docker image, it's not so bad?

**Comment by moderation** [comment]
I'm clearly in a minority but as I'm running Linux I like to compile from source. "Use docker" is the new "vagrant up". Compiling from source allows me to run from master. I've got it working now. Thanks.

**Comment by dlespiau** [comment]
There's nothing wrong with that :) I was just trying to think of ways to make the experience better. It could be making sure that the instructions do work out of the box on the major distros for instance (with a CI test) or at lest find out which minimal npm version we depend on. Will think some more.

Glad you have it working at the end!
