### ISSUE TITLE
jk validate

### ISSUE THREAD

**Issue by squaremo** [jkcfg/jk#235]
**Idea**

    jk validate [flags] file

runs the validation indicated by the flags on the file given. The file could be (design choice):

 1. a jk script to run, with the output being validated
 2. an arbitrary config file in one of the formats readable by jk

The latter is more orthogonal (to `jk run` and `jk generate`), and the former could be made convenient by other means, e.g., `jk generate --validate` (see below).

The flags might specify:

 - an OpenAPI schema
 - an OpenPolicyAgent policy
 - an arbitrary script or module to run against the file (or file output)

**Packaging validations**

It would be useful to be able to package validations, so they can be distributed. For example, the standard Kubernetes schemas and policy could be packaged with `@jkcfg/kubernetes`, to be referred to.

**Dispatching validation**

In the case that multiple files are being examined (e..g, with `jk generate --validate`), it will be necessary to have some kind of dispatch mechanism -- `deployments.app/v1` get this validation, `services.core/v1` get that validation.

**Validation in stdlib**

It may be necessary to invoke validation arbitrarily from within a jk script; in which case, having validation available in the standard library would be handy.

**`jk generate --validate`**

Building validation into `jk generate` makes sense too. The protocol for generate is that scripts export an array of { file, value }; this can be extended to support validations, and library functions that construct those arrays (e.g., in `@jkcfg/kubernetes/generate`) could include the appropriate validation.

**Comment by squaremo** [comment]
**Implementation musings, chapter one**

I had a look at OpenPolicyAgent, and it turned out that can compile (in a limited way) policies to WebAssembly (`wasm`), which as we know, will run natively in V8. This suggested it would be useful to be able to load wasm into the jk runtime. It's also the case that the Go compiler has a wasm backend; so in principle, validation code could be written in Go, compiled to wasm and made available directly to JavaScript as a module.

In practice, it's complicated. Adapting the generated wasm code to JavaScript requires a library (wasm_exec.js) with runtime support. There's a couple of problems with this particular bit of JS:

 - it depends on either Node.JS- or browser-provided procedures, like console.log
 - it uses require() rather than ES6 modules

It would likely be possible to write a runtime that avoided those problems. Is it worth it, at that point? It would be neat to be able to make these sorts of things available to JavaScript modules, without having to write more RPC code.

**Comment by squaremo** [comment]
**Implementation musings, chapter two**

Continuing with the OPA theme, it would be possible to either extend the set of RPC commands or to use a more generic RPC to embed the OPA interpreter and make it available to JavaScript. It's also possible to add builtin functions to the interpreter, when embedding it -- for example, a builtin for validating a document against a schema.

Assuming for the second that using OPA/Rego is a reasonable way to introduce validation, there are some ergonomic considerations:

 - Rego has a notion of `data` and `input`, where the data are a corpus of static documents, either supplied explicitly or reified from rules, and input is the document "in question"; this needs to be accounted for in the API for validation. One way would be to supply static documents and rules ahead of time in one (or more) calls, then do queries in further calls. But this implies there's some persistence to the documents, and that may introduce problems with scoping (e.g., how do you avoid modules polluting each other's data?)

 - How do people supply rules and policies? Rego is a language not especially alike to JavaScript; but there are reasons to allow "native" Rego to be loaded, e.g., so it can be shared with other uses of the policies.

**Comment by dlespiau** [comment]
I was thinking about funnelling everything through OPA. For instance, to validate the PromQL queries in grafana dashboards with promlint, it may be a bit too much work to ensure that's reachable through OPA/rego.

But maybe not?

**Comment by squaremo** [comment]
I don't think everything would have to go through OPA -- it's just available as a means of validation. For instance, I wouldn't expect to have to do something like

    jk validate -e 'some rego query` ./

I'd expect it to be wrapped in modules, so more like

```
import { query } from '@jkcfg/std/opa';

export function validate(doc) {
  return some_js_validation(doc) && query('some rego expression', doc);
}
```

**Comment by squaremo** [comment]
NB this leaves open the question of making, say, openapi schema validation available directly to JavaScript -- which might be a better way to start, even. There's nothing stopping us doing both! I mean aside from our mortal lifespans.
