### ISSUE TITLE
Rename unparse to stringify?

### ISSUE THREAD

**Issue by dlespiau** [jkcfg/jk#248]
`unparse` is a bit unusual, `stringify` has some mindshare with `JSON.stringify` and `unparse` could be seen as a general version `JSON.stringify` that understands other formats as well.

**Comment by dimitropoulos** [comment]
for what it's worth: the exceedingly popular csv library [papaparse](https://www.papaparse.com/) uses unparse.  I'm fairly sure this decision, though, predates JSON.stringify being added by douglas crockford.
