### ISSUE TITLE
Errors are printed to stdout instead of stderr

### ISSUE THREAD

**Issue by bryanlarsen** [jkcfg/jk#280]
I want to put this in my CI script:

    set -e
    jk generate --stdout infra/jk/install.js > /dev/null
    jk generate --stdout infra/jk/install.js | kubectl apply -f -

However, jk prints error messages to stdout instead of stderr and I don't get useful output.   At least this error goes to stdout rather than stderr.

   Promise rejected at @jkcfg/std/internal/deferred.js 0:0
   Error: open /work/threekit/core/users-service/jk/secrets.json: no such file or directory

**Comment by squaremo** [comment]
I am even a little tempted to change our fork of v8worker2 so that `V8Worker2.print()` prints to stderr, then use that directly from `std.log`. (Or similarly, adding a `log` to the global object and using that.)

**Comment by dlespiau** [comment]
We just released `0.3.1` which should this fixed. Do shout if you find problems! https://github.com/jkcfg/jk/releases/tag/0.3.1.
