### ISSUE TITLE
Feature Request: add base64 encoding/decoding (atob/btoa) to std

### ISSUE THREAD

**Issue by mflendrich** [jkcfg/jk#298]
I need conversion between plain text and base64 in order to work with k8s secrets.

**Comment by dlespiau** [comment]
There's an `encode` in the kubernetes library https://github.com/jkcfg/kubernetes/blob/master/src/base64.js. We've tried to leave the std lib quite simple and use support libraries instead. It's debatable, of course.

**Comment by errordeveloper** [comment]
@mflendrich did you try `dataString` (see https://godoc.org/k8s.io/api/core/v1#Secret)?

**Comment by mflendrich** [comment]
@errordeveloper `dataString` is not sufficient, because my jk use case needs to manipulate base64 strings elsewhere too.

@dlespiau thanks, `encode` in `kubernetes` seems to be what I needed!
