### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by jaxxstorm** [jkcfg/jk#300]
Is there a way to read environment variables with jk?

**Comment by squaremo** [comment]
Not at present. You would need to supply them via shell expansion and parameters, e.g.,

    jk run -p foobar="$FOOBAR" -c 'log(param.String("foobar"))'

This is a deliberate omission; the rationale being that everything from the "outside world" should be passed explicitly to a script, to rule out a source of unpredictable behaviour.

**Comment by jaxxstorm** [comment]
thanks!
