### ISSUE TITLE
Remove alpha banner

### ISSUE THREAD

**Issue by danielepolencic** [jkcfg/jk#314]
_Context: this issue originated [from this thread](https://twitter.com/errordeveloper/status/1216311058211725312)._

You should consider removing the "alpha banner":

> jk is still in very early stages. The standard library API isn't frozen and will most likely change. Feedback is most definitely welcome!

I understand that the API is in flux, but it's hard to promote the tool if the first thing you see is a warning suggesting that this is not ready for prime time.

**Comment by dlespiau** [comment]
That rings completely true :) Instead maybe we should document in the README somewhere the API guarantees before we reach 1.0.0, ie.

- There is no incompatibilities between patch versions: for a fixed `x` all 0.x.y versions are compatible.
- Minor versions may introduce some API changes. Those changes are documented in [deprecations.md](https://github.com/jkcfg/jk/blob/master/docs/deprecations.md).
