### ISSUE TITLE
Can't build 0.3.2 tag with jkcfg/build

### ISSUE THREAD

**Issue by GJKrupa** [jkcfg/jk#327]
I'm trying to build JK into a new container image using a multi-stage Docker build. The first step of the Dockerfile is as follows:

```
FROM jkcfg/build AS builder
ARG VERSION=0.3.2
WORKDIR /go/src/github.com/jkcfg
RUN git clone https://github.com/jkcfg/jk.git
WORKDIR /go/src/github.com/jkcfg/jk
RUN git checkout ${VERSION} && \
    make dep jk
```

I always prefer to build a tag rather than the current master branch as the image should be immutable and repeatable (ignoring that jkcfg/build isn't versioned).

This build fails with the following error:
```
# github.com/jkcfg/jk/pkg/std
pkg/std/std.go:212:18: cannot convert 1 (type untyped number) to type bool
pkg/std/std.go:212:18: invalid operation: args.Sync() == 1 (mismatched types bool and int)
make: *** [Makefile:11: jk] Error 2
```

If I remove the git checkout command to build the master branch then the build is successful.

**Comment by GJKrupa** [comment]
Workaround: I've managed to compile successfully by using the *previous* commit of the prebuilt repo (as follows):
```
FROM golang:1.14.0-buster AS builder
ARG VERSION=0.3.2
RUN mkdir -p /go/src/github.com/jkcfg
WORKDIR /go/src/github.com/jkcfg
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get update && \
    apt-get install -y git nodejs pkg-config make bash
RUN npm install -g typescript@3.8.3 && \
    git clone --branch ${VERSION} https://github.com/jkcfg/jk.git && \
    git clone https://github.com/jkcfg/prebuilt.git
WORKDIR /go/src/github.com/jkcfg/prebuilt
RUN git checkout 63da07bd13f30d9609451add37722aa207d82528 && \
    make install-linux-amd64
WORKDIR /go/src/github.com/jkcfg/jk
RUN make dep && \
    make jk
```

**Comment by squaremo** [comment]
That error comes from using flatc (flatbuffers compiler) 1.10.1 rather than 1.11.0. I was pretty sure `jkcfg/build` has the right version 🤔

**Comment by squaremo** [comment]
If I do this:

```
$ cat > Dockerfile <<EOF
> FROM jkcfg/build AS builder
> ARG VERSION=0.3.2
> WORKDIR /go/src/github.com/jkcfg
> RUN git clone https://github.com/jkcfg/jk.git
> WORKDIR /go/src/github.com/jkcfg/jk
> RUN git checkout ${VERSION} && \
>    make dep jk
> EOF
$ docker build .
```

then it successfully completes. Did I miss a step or misunderstand what is the problem?

**Comment by GJKrupa** [comment]
I'll give it another try but did you re-pull the image to make sure you have the most recent version of the latest tag in your layer cache?

**Comment by squaremo** [comment]
Fair call, yep, let' see:

```
$ docker pull jkcfg/build
Using default tag: latest
latest: Pulling from jkcfg/build
Digest: sha256:3aa0441b38edaa69bf63c85016a7459aa734b7d738b0fdcfc73fc7ec53ffd2a5
Status: Image is up to date for jkcfg/build:latest
docker.io/jkcfg/build:latest
```

If you do

```
docker run --rm -ti jkcfg/build
root@blah# flatc --version
```

what do you see?

**Comment by GJKrupa** [comment]
Not sure what's changed in my setup but the build is working now.
I'm seeing `flatc version 1.11.0` from the version check.

Apologies for wasting your time.

**Comment by squaremo** [comment]
All good! Happy you're back on track, however it happened :-)
