### ISSUE TITLE
Using params with std.Format.Raw

### ISSUE THREAD

**Issue by jaxxstorm** [jkcfg/jk#360]
I'm considering trying to generate a parameterized Makefile with `Raw` formatting, and not really understanding how that might look. Do you have a very simple exampleS?

**Comment by squaremo** [comment]
You could use a template library, say handlebars -- there's an example given here: https://github.com/jkcfg/jk/tree/master/examples/jk/handlebars

**Comment by jaxxstorm** [comment]
thanks, will give this a try!
