### ISSUE TITLE
Document building jk

### ISSUE THREAD

**Issue by dlespiau** [jkcfg/jk#45]
- building in docker image on linux, /README.md
- building stdlib, on OS X, or from from scratch on linux /build/README.md

**Comment by dholbach** [comment]
I think it'd be good to at least spell out the build requirements, e.g. `flatc`(?):

```sh
[daniel@reef jk ]$ make
std/generate.sh
std/generate.sh: line 7: flatc: command not found
make: *** [Makefile:14: std/build/std.js] Error 127
[daniel@reef jk ]$ 
```

**Comment by dlespiau** [comment]
yes, definitely!

`flatc` is the [flatbuffer](https://google.github.io/flatbuffers/) compiler, which has be be compiled by hand.

For now options include:
- Download the latest release: https://github.com/jkcfg/jk/releases
- On linux, you can run the build in a docker container that has all the dependencies needed: `./run-in-docker.sh make`. At the end of that, you should have a `jk` binary in the project root directory
- On mac, one can git clone https://github.com/jkcfg/prebuilt, run `make install` there to install the needed deps and then `make` just works
- We could offer prebuilt deps for Linux as well

On l

**Comment by dholbach** [comment]
As this issue is about documenting how to build `jk`, I like the idea of running the build in Docker. That sounds straight-forward and requiring `make` and `docker` shouldn't be an issue. :-)
