### ISSUE TITLE
std.read() relative paths should be resolved against the script path

### ISSUE THREAD

**Issue by dlespiau** [jkcfg/jk#61]
There's definitely argument for both sides of the fence:
  - relative to the current directory
  - relative to the script directory

I expect that, for the configuration case, the script will want to source (script-)local assets rather than files in the current directory.

**Comment by squaremo** [comment]
Or the ability to do either? I can think of two ways of doing this:

 - a `-C` flag meaning "make this the working directory"
 - a subcommand which means "generate from the path given" (i.e., make the working directory the dir of the script named)

The most familiar way to behave is to treat paths relative to the working directory, which would indicate a `-C` flag.

Followup question: how does the script itself get resolved? An expected mode of use is to have a directory with the generation script plus all other required files. Say that's `a/b/c` and the script is `a/b/c/generate.js` -- do I do

    $ jk run -C ./a/b/c ./a/b/c/generate.js

or

    $ jk run -C ./a/b/c generate.js

? And if the latter, how do I run a script that's somewhere else? (One way is to make `./` or `../` significant -- but perhaps a bit subtle).

**Comment by dlespiau** [comment]
So I think we have "solved" that question now between the `--input-directory` option and #134. Closing.
