### ISSUE TITLE
Write several objects to a file

### ISSUE THREAD

**Issue by squaremo** [jkcfg/jk#93]
While writing kubernetes examples, I occasionally found I had a set (OK, array) of objects and wanted to output them all to the console as a YAML "stream", like

```
---
resource: one
---
resource: two
```

It's possible to do this by hacking std.log (since output to stdout is necessarily concatenated), but that doesn't extend to outputting to a file.

I can think of a few ways of accommodating this wish:

 1. have formats for each of YAMLStream and JSONStream
 2. switch the argument order in `write` around a bit and make the values-to-write parameters a vararg
 3. have a separate option `{ stream: true }` for specifying that [...] should be written as a stream, rather than as an array value
 4. let `write` append to the file it's given, and assume writes after the first should be concatenated according to the format

**Comment by dlespiau** [comment]
We'll also need this support for `std.read` and I think the write and read parts should look the same. That removes option 2. and 4. I believe.

It's a close call between defining new formats and the nice orthogonal `{ stream: true }`. Looking at the [Wikipedia page](https://en.wikipedia.org/wiki/JSON_streaming) for JSON Streaming, there are a few different ways to do that, I think we'd implement "Concatenated JSON streaming" which supports both "Line-delimited JSON" and "Concatenated JSON". There are other options though and, to not paint ourselves into a corner, going the format route would allow us to define additional streaming types such as `JsonTextSequences` (RFC 7464).

The above means I cast my vote for defining new formats, we could start by `YAMLStream` as it's probably what we'd need first.

**Comment by squaremo** [comment]
I agree that `read` working in a similar way is good, and that 4) would be weird (for write, and more so for read).

2) for reading would be something like "always assume a stream, and always return an array of values". While this covers the bases, it would be a bit awkward to use. When expecting a single value, you'd have to remember to get the array item(s):

    const [ value ] = await read('blah.json');

I agree on the format vs stream (1 v 3); another thing in its favour is that {format, stream=true} combinations won't always make sense (though they just about do now).

An option that I didn't mention is representing streams as objects; in this case, you'd have `streamWriter` and `streamReader`, which are given files (possibly `''` meaning stdout or stdin respectively), and have a write or read method accepting / returning a single value. One advantage of those is that you don't have to collect all the values first -- you can write them out as you construct them (and pass them as values, etc.)

**Comment by dlespiau** [comment]
With #136 merged, I believe we can close this. If/when we need something else on top of #136, we should open separate issues.
